id: A733394BA
title: The Twenty-Eight Commitments
type: translation
pechas:
- IA99B8D63
- I8BD5567C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:02.947712
  last_modified_at: 2023-01-04 11:34:02.947723
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  IA99B8D63/9DD3: 2B44
  I8BD5567C/724E: 2B44
